version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: zippie-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: newpassword
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: zippie-app
    restart: always
    env_file: .env
    ports:
      - "3000:5000"  # Map host port 3000 to container port 5000
    depends_on:
      postgres:
        condition: service_healthy  # Wait for database to be ready
    environment:
      DATABASE_URL: postgresql://postgres:newpassword@postgres:5432/taskdb  # Use service name 'postgres'
      FLASK_RUN_HOST: 0.0.0.0  # Allow external connections
      FLASK_RUN_PORT: 5000     # Ensure Flask runs on port 5000

volumes:
  pgdata: